class Cards {
  constructor() {
    this.cards = [
      "clubs2",
      "clubs3",
      "clubs4",
      "clubs5",
      "clubs5",
      "clubs6",
      "clubs6",
      "clubs7",
      "clubs7",
      "clubs8",
      "clubs8",
      "clubs9",
      "clubs9",
      "clubs10",
      "clubs10",
      "clubsAce",
      "clubsAce",
      "diamonds2",
      "diamonds3",
      "diamonds4",
      "diamonds5",
      "diamonds5",
      "diamonds6",
      "diamonds7",
      "diamonds6",
      "diamonds7",
      "diamonds8",
      "diamonds8",
      "diamonds9",
      "diamonds9",
      "diamonds10",
      "diamonds10",
      "diamondsAce",
      "diamondsAce",
      "hearts2",
      "hearts3",
      "hearts4",
      "hearts5",
      "hearts5",
      "hearts6",
      "hearts6",
      "hearts7",
      "hearts7",
      "hearts8",
      "hearts8",
      "hearts9",
      "hearts9",
      "hearts10",
      "hearts10",
      "heartsAce",
      "heartsAce",
      "spades2",
      "spades3",
      "spades4",
      "spades5",
      "spades5",
      "spades6",
      "spades6",
      "spades7",
      "spades7",
      "spades8",
      "spades8",
      "spades9",
      "spades9",
      "spades10",
      "spades10",
      "spadesAce",
      "spadesAce",
      "brick",
      "brick",
      "brick",
    ];
  }

  getCards() {
    return this.cards;
  }
}

module.exports = Cards;
